
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Table table7;
	
	private global::Gtk.Entry entry3;
	
	private global::Gtk.Entry entry4;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Table table8;
	
	private global::Gtk.Entry entry5;
	
	private global::Gtk.Entry entry6;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Table table9;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.Button button7;
	
	private global::Gtk.Button button8;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Button button9;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.table7 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table7.Name = "table7";
		this.table7.RowSpacing = ((uint)(6));
		this.table7.ColumnSpacing = ((uint)(6));
		// Container child table7.Gtk.Table+TableChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.table7.Add (this.entry3);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table7 [this.entry3]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.table7.Add (this.entry4);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table7 [this.entry4]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
		this.table7.Add (this.label2);
		// Container child table7.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
		this.table7.Add (this.label3);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table7 [this.label3]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		this.hbox1.Add (this.table7);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.table7]));
		w5.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.table8 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table8.Name = "table8";
		this.table8.RowSpacing = ((uint)(6));
		this.table8.ColumnSpacing = ((uint)(6));
		// Container child table8.Gtk.Table+TableChild
		this.entry5 = new global::Gtk.Entry ();
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.table8.Add (this.entry5);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table8 [this.entry5]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.entry6 = new global::Gtk.Entry ();
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.table8.Add (this.entry6);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table8 [this.entry6]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Address");
		this.table8.Add (this.label4);
		// Container child table8.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("City");
		this.table8.Add (this.label5);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table8 [this.label5]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		this.hbox1.Add (this.table8);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.table8]));
		w10.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table9 = new global::Gtk.Table (((uint)(2)), ((uint)(4)), false);
		this.table9.Name = "table9";
		this.table9.RowSpacing = ((uint)(6));
		this.table9.ColumnSpacing = ((uint)(6));
		// Container child table9.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Create");
		this.table9.Add (this.button3);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table9 [this.button3]));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table9.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Read");
		this.table9.Add (this.button4);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table9 [this.button4]));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table9.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Update");
		this.table9.Add (this.button5);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table9 [this.button5]));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table9.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Delete");
		this.table9.Add (this.button6);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table9 [this.button6]));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table9.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("prev");
		this.table9.Add (this.button7);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table9 [this.button7]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table9.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button ();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("next");
		this.table9.Add (this.button8);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table9 [this.button8]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(3));
		w17.RightAttach = ((uint)(4));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table9);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table9]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("#Status:");
		this.hbox5.Add (this.label9);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label9]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = ".";
		this.hbox5.Add (this.label11);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label11]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("#Client:");
		this.hbox6.Add (this.label10);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label10]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = ".";
		this.hbox6.Add (this.label12);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label12]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox2.Add (this.hbox6);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.hbox4.Add (this.vbox2);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox2]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("#Products:");
		this.hbox3.Add (this.label6);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = ".";
		this.hbox3.Add (this.label8);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label8]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		this.hbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Xalign = 0F;
		this.hbox2.Add (this.label7);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label7]));
		w30.Position = 1;
		w30.Expand = false;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w31.Position = 1;
		w31.Expand = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("Terminar");
		this.vbox4.Add (this.button9);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button9]));
		w32.Position = 2;
		this.vbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
		w33.Position = 2;
		w33.Expand = false;
		w33.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 521;
		this.DefaultHeight = 268;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button8.Clicked += new global::System.EventHandler (this.nextClient);
		this.button7.Clicked += new global::System.EventHandler (this.prevClient);
		this.button6.Clicked += new global::System.EventHandler (this.deleteClient);
		this.button5.Clicked += new global::System.EventHandler (this.updateClient);
		this.button4.Clicked += new global::System.EventHandler (this.readClient);
		this.button3.Clicked += new global::System.EventHandler (this.createClient);
	}
}
